In [39]:
import os
print(os.getcwd())

d:\CDW


In [40]:
import pandas as pd
df = pd.read_csv('D:/CDW/CDW_Internship/all_kindle_review.csv')
reviews = df[['reviewText', 'rating']]

In [41]:
reviews

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       3
1      Great short read.  I didn't want to put it dow...       5
2      I'll start by saying this is the first of four...       3
3      Aggie is Angela Lansbury who carries pocketboo...       3
4      I did not expect this type of book to be in li...       4
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

[12000 rows x 2 columns]

In [42]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Sugan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [43]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [44]:
corpus=[]
for i in range(0,len(reviews)):
    review=re.sub('[^a-zA-z]',' ',reviews['reviewText'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [45]:
corpus


['jace rankin may short noth mess man haul saloon undertak know famou bounti hunter oregon shot man saloon finish year long quest aveng sister murder tri figur next snotti nose farm boy rescu gang bulli offer money kill man forc ranch reluctantli agre bring man justic kill outright first need tell sister widow news kyla kyle springer bailey ride trail sleep ground past month tri find jace want reveng man kill husband took ranch amongst crime keen detour jace want take realiz option hide behind boy persona best tri keep pace confront along way get shot jace discov kyle kyla come clean whole reason need scoundrel dead hope still help book share touch moment slow bloom romanc kyla find good reason fear men hide behind boy persona watch jace slowli pull shell help conquer fear endear pain real deepli root disappear face sexi neither understand avers marriag magic disappear round nooki would man drift town town entir adult life man kill fair share men along way feel make good husband father

In [46]:
## Output Features
y=pd.get_dummies(reviews['rating'])

In [47]:
y=y.iloc[:,0].values

In [48]:
y

array([False, False, False, False, False, False, False, False, False, False,  True, False,  True, False, False, False, False,  True, False, False, False, False, False, False, False,  True, False,  True, False, False, ..., False,  True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,  True, False, False, False, False, False, False, False, False,  True, False], shape=(12000,))

In [49]:
#Create Bag of Words

In [50]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [51]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [52]:
len(X_train),len(y_train)

(9600, 9600)

In [53]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [54]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [55]:
cv.vocabulary_

{'pick': np.int64(1583),
 'amazon': np.int64(68),
 'freebi': np.int64(853),
 'cover': np.int64(492),
 'art': np.int64(114),
 'caught': np.int64(350),
 'attent': np.int64(128),
 'figur': np.int64(788),
 'realli': np.int64(1752),
 'want': np.int64(2361),
 'like': np.int64(1243),
 'book': np.int64(221),
 'go': np.int64(910),
 'read': np.int64(1711),
 'next': np.int64(1461),
 'seri': np.int64(1915),
 'sure': np.int64(2143),
 'end': np.int64(665),
 'take': np.int64(2158),
 'break': np.int64(298),
 'anoth': np.int64(84),
 'pretti': np.int64(1634),
 'much': np.int64(1422),
 'forc': np.int64(829),
 'return': np.int64(1813),
 'finish': np.int64(796),
 'stori': np.int64(2064),
 'kind': np.int64(1179),
 'disjoint': np.int64(599),
 'main': np.int64(1322),
 'charact': np.int64(362),
 'felt': np.int64(778),
 'vamp': np.int64(2334),
 'love': np.int64(1292),
 'weak': np.int64(2384),
 'woman': np.int64(2434),
 'instead': np.int64(1098),
 'vampir': np.int64(2335),
 'fairi': np.int64(744),
 'half': np.in

In [56]:
from sklearn.naive_bayes import MultinomialNB

In [57]:
sentimental_model=MultinomialNB().fit(X_train,y_train)

In [58]:
y_pred=sentimental_model.predict(X_test)

In [59]:
from sklearn.metrics import accuracy_score,classification_report

In [60]:
accuracy_score(y_test,y_pred)

0.8370833333333333

In [61]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.93      0.87      0.90      2007
        True       0.50      0.68      0.58       393

    accuracy                           0.84      2400
   macro avg       0.72      0.77      0.74      2400
weighted avg       0.86      0.84      0.85      2400



In [62]:
#Creating Td-idf model

In [63]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [64]:
len(corpus)

12000

In [65]:
len(X_train),len(X_test)


(9600, 2400)

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [67]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0632, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.0538, 0.04, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0559, 0, 0, 0, 0.0818, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0.181, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],


In [68]:
tv.vocabulary_

{'book': np.int64(219),
 'good': np.int64(902),
 'short': np.int64(1932),
 'could': np.int64(471),
 'read': np.int64(1691),
 'seri': np.int64(1898),
 'love': np.int64(1278),
 'book good': np.int64(240),
 'good short': np.int64(911),
 'book read': np.int64(260),
 'read book': np.int64(1695),
 'book seri': np.int64(266),
 'sorri': np.int64(1997),
 'meant': np.int64(1347),
 'writer': np.int64(2477),
 'serious': np.int64(1905),
 'hate': np.int64(975),
 'leav': np.int64(1207),
 'neg': np.int64(1431),
 'review': np.int64(1796),
 'much': np.int64(1404),
 'time': np.int64(2223),
 'skip': np.int64(1966),
 'want': np.int64(2362),
 'hurt': np.int64(1045),
 'anyon': np.int64(93),
 'feel': np.int64(762),
 'lack': np.int64(1186),
 'charact': np.int64(356),
 'develop': np.int64(566),
 'protagonist': np.int64(1644),
 'zero': np.int64(2497),
 'fact': np.int64(730),
 'say': np.int64(1849),
 'far': np.int64(746),
 'concern': np.int64(438),
 'even': np.int64(688),
 'possibl': np.int64(1600),
 'noth': np.i

In [69]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [70]:
#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [71]:
from sklearn.metrics import accuracy_score,classification_report
score=accuracy_score(y_test,y_pred)
print(score)

0.8479166666666667


In [72]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.99      0.85      0.92      2320
        True       0.15      0.80      0.26        80

    accuracy                           0.85      2400
   macro avg       0.57      0.82      0.59      2400
weighted avg       0.96      0.85      0.89      2400

