In [2]:
!pip install bertviz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.6/157.6 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.2/139.2 kB 10.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 86.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.2/84.2 kB 7.0 MB/s eta 0:00:00


In [3]:
from transformers import pipeline, set_seed, AutoTokenizer, AutoModelForCausalLM, AutoModel
from torch import tensor, numel
from bertviz import model_view, head_view
import torch
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity

set_seed(42)

In [4]:
# pipeline object in transformers provides easy access to transformer usage
MODEL = 'gpt2'

generator = pipeline('text-generation', model=MODEL)

# finish the sentence
generator("Today is the great day", max_length=30, num_return_sequences=3)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'Today is the great day of ours!"\n\n"We\'re going to see a great party in this town of yours, and the president and I'},
 {'generated_text': 'Today is the great day to take back the public and to stand up for who we are as a country. As Americans we need to be very united'},
 {'generated_text': 'Today is the great day of the Great American Revolution, where we were all patriots and we rose to assert ourselves. We have been waiting so long'}]

In [5]:
# load up a tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL)

'Sinan' in tokenizer.get_vocab()

False

In [8]:
tokenizer.encode('today is the great day')

[40838, 318, 262, 1049, 1110]

In [9]:
# encode a string and then convert the ids back into tokens. Note the Ġ character denoting a space before the token
tokenizer.convert_ids_to_tokens(tokenizer.encode('Sinan loves a beautiful day'))

['Sin', 'an', 'Ġloves', 'Ġa', 'Ġbeautiful', 'Ġday']

In [10]:
tokenizer.encode('Sinan loves a beautiful day')  # ids

[46200, 272, 10408, 257, 4950, 1110]

In [11]:

encoded = tokenizer.encode('Sinan loves a beautiful day', return_tensors='pt')  # as a pytorch tensor

encoded

tensor([[46200,   272, 10408,   257,  4950,  1110]])

In [12]:
# load up a tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForCausalLM.from_pretrained(MODEL)

In [13]:
model


GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2SdpaAttention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [14]:
encoded

tensor([[46200,   272, 10408,   257,  4950,  1110]])

In [15]:
model.transformer.wte(encoded)

tensor([[[ 0.0295, -0.0479,  0.1235,  ..., -0.1539, -0.0276,  0.0994],
         [-0.1253, -0.0356,  0.0570,  ..., -0.0876, -0.0628,  0.0048],
         [-0.0758, -0.0843, -0.0159,  ..., -0.2232, -0.0390, -0.0899],
         [-0.0506,  0.0056,  0.0471,  ...,  0.0425,  0.0735, -0.0384],
         [ 0.0535,  0.1676,  0.0133,  ...,  0.0880,  0.0411,  0.1544],
         [-0.1379, -0.0294, -0.0026,  ..., -0.0966, -0.0726,  0.1160]]],
       grad_fn=<EmbeddingBackward0>)

In [16]:
model.transformer.wte(encoded).shape  # 1 item in batch x 6 tokens x token dimension

torch.Size([1, 6, 768])

In [17]:
model.transformer.wpe(tensor([0, 1, 2, 3, 4, 5]).reshape(1, 6)).shape  # manually create position vectors

torch.Size([1, 6, 768])

In [18]:
# create GPT input
initial_input = model.transformer.wte(encoded) + model.transformer.wpe(tensor([0, 1, 2, 3, 4, 5]).reshape(1, 6))

initial_input.shape

torch.Size([1, 6, 768])

In [19]:
initial_input = model.transformer.drop(initial_input)  # run our input through the model's initual dropout later
initial_input

tensor([[[ 0.0107, -0.2453,  0.1275,  ..., -0.1969,  0.0006,  0.1539],
         [-0.1013, -0.0894, -0.0378,  ..., -0.0534, -0.0527,  0.0046],
         [-0.0716, -0.1690,  0.0386,  ..., -0.2034, -0.0197, -0.1113],
         [-0.0509, -0.0682,  0.1526,  ...,  0.0527,  0.0912, -0.0455],
         [ 0.0612,  0.1425,  0.1402,  ...,  0.0964,  0.0510,  0.1474],
         [-0.1283, -0.0632,  0.1287,  ..., -0.0907, -0.0655,  0.1085]]],
       grad_fn=<AddBackward0>)

In [20]:
model.lm_head

Linear(in_features=768, out_features=50257, bias=False)

In [21]:
for module in model.transformer.h:  # run the initial_input through every decoder in the stack
    initial_input = module(initial_input)[0]

initial_input = model.transformer.ln_f(initial_input)  # and then the final layer norm

In [22]:

initial_input

tensor([[[ 0.0542, -0.0179, -0.3388,  ..., -0.0948, -0.1067,  0.0129],
         [-0.4805,  0.1008, -0.7313,  ...,  0.0471, -0.4113,  0.0902],
         [ 0.0344, -0.2259, -0.5293,  ..., -0.1202,  0.1355,  0.2287],
         [-0.2374,  0.1787,  0.1845,  ..., -0.4057, -0.3617, -0.1861],
         [ 0.0235,  0.1212, -1.0182,  ..., -0.0597,  0.0020, -0.2220],
         [ 0.1206, -0.5034, -1.5260,  ..., -0.3367, -0.2821, -0.0410]]],
       grad_fn=<NativeLayerNormBackward0>)

In [23]:
# same as just running through the model
(initial_input == model(encoded, output_hidden_states=True).hidden_states[-1]).all()

tensor(True)

In [24]:
model(encoded).logits.shape

torch.Size([1, 6, 50257])

In [25]:
total_params = 0
for param in model.parameters():
    total_params += numel(param)

print(f'Number of params: {total_params:,}')

Number of params: 124,439,808


**Masked multi-headed attention**

In [26]:
import torch
import pandas as pd

In [27]:
phrase = 'My friend was right about this class. It is so fun!'
encoded_phrase = tokenizer(phrase, return_tensors='pt')

response = model(**encoded_phrase, output_attentions=True, output_hidden_states=True)

len(response.attentions)

`GPT2SdpaAttention` is used but `torch.nn.functional.scaled_dot_product_attention` does not support `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.


12

In [28]:
encoded_phrase

{'input_ids': tensor([[3666, 1545,  373,  826,  546,  428, 1398,   13,  632,  318,  523, 1257,
            0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [29]:

response.attentions[-1].shape  # represtnations from the final decoder

torch.Size([1, 12, 13, 13])

In [30]:
encoded_phrase['input_ids'].shape

torch.Size([1, 13])

In [31]:
tokens = tokenizer.convert_ids_to_tokens(encoded_phrase['input_ids'][0])

tokens

['My',
 'Ġfriend',
 'Ġwas',
 'Ġright',
 'Ġabout',
 'Ġthis',
 'Ġclass',
 '.',
 'ĠIt',
 'Ġis',
 'Ġso',
 'Ġfun',
 '!']

In [32]:
# Layer index 9, head 0. Check out the almost 60% attention the token it is giving to the token class
arr = response.attentions[9][0][0]

n_digits = 3

attention_df = pd.DataFrame((torch.round(arr * 10**n_digits) / (10**n_digits)).detach()).applymap(float)

attention_df.columns = tokens
attention_df.index = tokens

attention_df

<ipython-input-32-d6243f37e893>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  attention_df = pd.DataFrame((torch.round(arr * 10**n_digits) / (10**n_digits)).detach()).applymap(float)


My  Ġfriend   Ġwas  Ġright  Ġabout  Ġthis  Ġclass      .    ĠIt  \
My       1.000    0.000  0.000   0.000   0.000  0.000   0.000  0.000  0.000   
Ġfriend  0.968    0.032  0.000   0.000   0.000  0.000   0.000  0.000  0.000   
Ġwas     0.824    0.145  0.031   0.000   0.000  0.000   0.000  0.000  0.000   
Ġright   0.979    0.008  0.007   0.005   0.000  0.000   0.000  0.000  0.000   
Ġabout   0.979    0.008  0.004   0.005   0.005  0.000   0.000  0.000  0.000   
Ġthis    0.924    0.031  0.007   0.006   0.016  0.016   0.000  0.000  0.000   
Ġclass   0.946    0.005  0.001   0.001   0.001  0.002   0.044  0.000  0.000   
.        0.691    0.013  0.003   0.003   0.002  0.006   0.269  0.013  0.000   
ĠIt      0.318    0.003  0.003   0.003   0.006  0.018   0.599  0.018  0.032   
Ġis      0.331    0.006  0.002   0.002   0.003  0.018   0.533  0.013  0.062   
Ġso      0.141    0.010  0.005   0.004   0.004  0.026   0.645  0.023  0.096   
Ġfun     0.532    0.015  0.003   0.002   0.001  0.002   0.317  0.029  0.035   
!        0.527    0.008  0.003   0.001   0.001  0.003   0.245  0.026  0.034   

           Ġis    Ġso   Ġfun      !  
My       0.000  0.000  0.000  0.000  
Ġfriend  0.000  0.000  0.000  0.000  
Ġwas     0.000  0.000  0.000  0.000  
Ġright   0.000  0.000  0.000  0.000  
Ġabout   0.000  0.000  0.000  0.000  
Ġthis    0.000  0.000  0.000  0.000  
Ġclass   0.000  0.000  0.000  0.000  
.        0.000  0.000  0.000  0.000  
ĠIt      0.000  0.000  0.000  0.000  
Ġis      0.030  0.000  0.000  0.000  
Ġso      0.041  0.003  0.000  0.000  
Ġfun     0.014  0.003  0.047  0.000  
!        0.012  0.007  0.046  0.089

In [33]:
head_view(response.attentions, tokens)

<IPython.core.display.Javascript object>

In [34]:
tokens = tokenizer.convert_ids_to_tokens(encoded_phrase['input_ids'][0])
model_view(response.attentions, tokens)

<IPython.core.display.Javascript object>

In [35]:
response.hidden_states[-1].shape

torch.Size([1, 13, 768])

In [36]:
response.logits

tensor([[[ -33.0735,  -32.3349,  -35.2379,  ...,  -38.3576,  -38.4758,
           -33.0943],
         [ -98.8075,  -98.9730, -105.2267,  ..., -109.0421, -104.7381,
          -101.0802],
         [-131.2765, -130.8178, -135.2055,  ..., -138.3586, -134.9846,
          -134.1658],
         ...,
         [-120.6479, -122.7569, -127.1870,  ..., -130.4343, -129.5816,
          -125.1274],
         [ -73.8157,  -78.6168,  -85.3994,  ...,  -91.8286,  -91.7845,
           -81.4570],
         [-134.7547, -134.9495, -136.2912,  ..., -147.1822, -148.1732,
          -130.7045]]], grad_fn=<UnsafeViewBackward0>)

In [37]:
response.logits.shape

torch.Size([1, 13, 50257])

In [38]:
# look at the top next token in the auto-regressive language modelling task
pd.DataFrame(
    zip(tokens, tokenizer.convert_ids_to_tokens(response.logits.argmax(2)[0])),
    columns=['Sequence up until', 'Next token with highest probability']
)

Sequence up until Next token with highest probability
0                 My                                   Ċ
1            Ġfriend                                   ,
2               Ġwas                                  Ġa
3             Ġright                                   .
4             Ġabout                               Ġthat
5              Ġthis                                   .
6             Ġclass                                   .
7                  .                                  ĠI
8                ĠIt                                  's
9                Ġis                                  Ġa
10               Ġso                          Ġimportant
11              Ġfun                                 Ġto
12                 !                                  ĠI

In [39]:
generator('My friend was right', max_length=12, num_return_sequences=5)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'My friend was right to try but so was I.\n'},
 {'generated_text': "My friend was right in the '90s when we played"},
 {'generated_text': 'My friend was right.\n\nOne day when there came'},
 {'generated_text': 'My friend was right. "I have to do something"'},
 {'generated_text': 'My friend was right here to check out her," the driver'}]

In [40]:
generator(phrase, max_length=20, num_return_sequences=1, do_sample=False)  # greedy search

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'My friend was right about this class. It is so fun! I love it! I love the'}]

In [41]:
generator(phrase, max_length=20, num_return_sequences=1, do_sample=True)  # greedy search with sampling

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'My friend was right about this class. It is so fun!\n\nThe kids are not allowed'}]

**Parameters**

In [42]:
from transformers import AutoTokenizer

# Use the id of the model you want to use
# GPT-2 "openai-community/gpt2"
# Qwen "Qwen/Qwen2-0.5B"
# SmolLM "HuggingFaceTB/SmolLM-135M"

prompt = "It was a dark and stormy"
tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
input_ids = tokenizer(prompt).input_ids
input_ids

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[1026, 373, 257, 3223, 290, 6388, 88]

In [43]:
for t in input_ids:
    print(t, "\t:", tokenizer.decode(t))

1026 	: It
373 	:  was
257 	:  a
3223 	:  dark
290 	:  and
6388 	:  storm
88 	: y


**Prediction - Top_K**

In [44]:
# We tokenize again but specifying the tokenizer that we want it to
# return a PyTorch tensor, which is what the model expects,
# rather than a list of integers
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

outputs = model(input_ids)
outputs.logits.shape  # An output for each input token

torch.Size([1, 7, 50257])

In [45]:
final_logits = model(input_ids).logits[0, -1]  # The last set of logits
final_logits.argmax()  # The position of the maximum

tensor(1755)

In [46]:
tokenizer.decode(final_logits.argmax())

' night'

In [47]:
import torch

top10_logits = torch.topk(final_logits, 10)
for index in top10_logits.indices:
    print(tokenizer.decode(index))

 night
 day
 evening
 morning
 afternoon
 summer
 time
 winter
 weekend
,


In [48]:
top10 = torch.topk(final_logits.softmax(dim=0), 10)
for value, index in zip(top10.values, top10.indices):
    print(f"{tokenizer.decode(index):<10} {value.item():.2%}")

 night     46.18%
 day       23.46%
 evening   5.87%
 morning   4.42%
 afternoon 4.11%
 summer    1.34%
 time      1.33%
 winter    1.22%
 weekend   0.39%
,          0.38%


**Max Tokens**

In [ ]:
output_ids = model.generate(input_ids, max_new_tokens=20)
decoded_text = tokenizer.decode(output_ids[0])

print("Input IDs", input_ids[0])
print("Output IDs", output_ids)
print(f"Generated text: {decoded_text}")

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


Input IDs tensor([1026,  373,  257, 3223,  290, 6388,   88])
Output IDs tensor([[ 1026,   373,   257,  3223,   290,  6388,    88,  1755,    13,   383,
          2344,   373, 19280,    11,   290,   262, 15114,   547,  7463,    13,
           383,  2344,   373, 19280,    11,   290,   262]])
Generated text: It was a dark and stormy night. The wind was blowing, and the clouds were falling. The wind was blowing, and the


**Beams**

In [ ]:
beam_output = model.generate(
    input_ids,
    num_beams=5,
    max_new_tokens=30,
)

print(tokenizer.decode(beam_output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was a dark and stormy night.

"It was dark and stormy," he said.

"It was dark and stormy," he said.




In [ ]:
beam_output = model.generate(
    input_ids,
    num_beams=5,
    repetition_penalty=2.0,
    max_new_tokens=38,
)

print(tokenizer.decode(beam_output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was a dark and stormy night.

"I'm not sure what happened, but I don't know if it was an accident or something," he said.

Police say they're still trying to determine


**Do Sample**

In [ ]:
from transformers import set_seed

# Setting the seed ensures we get the same results every time we run this code
set_seed(70)

sampling_output = model.generate(
    input_ids,
    do_sample=True,
    max_new_tokens=34,
    top_k=0,  # We'll come back to this parameter
)

print(tokenizer.decode(sampling_output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was a dark and stormy day until it broke down the big canvas on my sleep station, making me money dilapidated, and, with a big soothing mug, I surrendered to the rolu


**Temperature**

In [ ]:
sampling_output = model.generate(
    input_ids,
    do_sample=True,
    temperature=0.4,
    max_new_tokens=40,
    top_k=0,
)

print(tokenizer.decode(sampling_output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was a dark and stormy night in the city, and the sky was dark and dark. It wasgood for the sun to shine. It was a day of joy. It was a day of joy Rhino was in the middle


In [ ]:
sampling_output = model.generate(
    input_ids,
    do_sample=True,
    temperature=0.001,
    max_new_tokens=40,
    top_k=0,
)

print(tokenizer.decode(sampling_output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was a dark and stormy night. The wind was blowing, and the clouds were falling. The wind was blowing, and the clouds were falling. The wind was blowing, and the clouds were falling. The wind was blowing,


In [ ]:
sampling_output = model.generate(
    input_ids,
    do_sample=True,
    temperature=3.0,
    max_new_tokens=40,
    top_k=0,
)

print(tokenizer.decode(sampling_output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was a dark and stormy time Robinson lower display magn Simon launching warmth cube lightsaber pil Welshatoryfaith317build thirty Lucy mixShot disapproval newplings Seven presentation laced & laced Einstein award drug camouflage 451 dietary downloading participants / pay Power delegated


**Top-K**

In [ ]:
sampling_output = model.generate(
    input_ids,
    do_sample=True,
    max_new_tokens=40,
    top_k=5,
)

print(tokenizer.decode(sampling_output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was a dark and stormy evening. It was a time of mourning, of mourning for those who had lost loved ones, of mourning for the loss of those who had been murdered. It was a time of mourning, a time


**Top - P**

In [ ]:
sampling_output = model.generate(
    input_ids,
    do_sample=True,
    max_new_tokens=40,
    top_p=0.94,
    top_k=0,
)

print(tokenizer.decode(sampling_output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was a dark and stormy day and some people were not there - I was hoping for some sort of action. I didn't see the fire in the sky but had to leave the location to get to the chapel as I was
